version: '3.1'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  scraper-base:
    build: .
    image: scraper-base:latest

  mpreis-scraper: &scraper-template
    image: scraper-base:latest
    depends_on: [scraper-base]
    #command: ["./wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "./run-spider.sh"]
    command: ["./run-spider.sh", "MpreisShop"]
    environment:
      PYTHONUNBUFFERED: 0
      SUPERMARKET_DATA_DIR: /project/data
      COMMAND_EXECUTOR: http://selenium:4444/wd/hub
    volumes:
      - ${SUPERMARKET_DATA_DIR}:/project/data
    links:
      - selenium
  alnatura-scraper:
    <<: *scraper-template
    command: ["./run-spider.sh", "AlnaturaShop"]

